version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskpilot-src
    ports:
      - "6060:6060"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
